Address virtual dev review feedback
- In the examples README.md, use the name
  of the merlin-tensorflow container in the
  sample command and revise the README so
  it no longer references a single notebook.
- Specify scikit-learn < 1.2 as a dependency
  to sidestep the `AttributeError: 'RandomForestClassifier'
  object has no attribute 'n_features_'` error.